In [2]:
import pandas as pd 
import numpy as np

In [3]:
#!pip install pandas numpy openpyxl

In [4]:
!pwd

/Users/awf/Projects/python/streamlit/traitement_sae

In [5]:
#filename = 'C:/Users/albert-marc.talla/Desktop/test/Taux de régularité DSP - 18092024131617.xlsx'

In [11]:
#!pip install openpyxl
!pip install openpyxl

Requirement already satisfied: openpyxl in /usr/local/lib/python3.11/site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in /usr/local/lib/python3.11/site-packages (from openpyxl) (1.1.0)

[notice] A new release of pip is available: 24.0 -> 24.2
[notice] To update, run: python3.11 -m pip install --upgrade pip

In [4]:
filename = "./mobirecord_declarations_export.xlsx"
df = pd.read_excel(filename)

In [5]:
df.head(50)

,Numéro,Statut,Création,Heure création,Date évènement,Heure début,Heure fin,Déclarant,Agent,Catégorie personnel,Matériel,Ligne,Direction,Type,Catégorie,Sous-catégorie,Consequences,Précisions
0,31097,En cours,21/08/2024,09:18,21/08/2024,09:03,09:17,MALKI MOURAD (606363),NaN,NaN,NaN,NaN,NaN,CIRCULATION - REGULATION,Régulation,Retard,Réseau interrompu / retardé,NaN
1,31096,En cours,21/08/2024,09:00,21/08/2024,07:13,NaN,MALKI MOURAD (606363),JALLOUL MOHAMED (606783),COND,207023.0,NaN,NaN,VEHICULES,Signalement en ligne,Bloquant,NaN,NaN
2,31095,En cours,21/08/2024,07:13,21/08/2024,07:11,NaN,MALKI MOURAD (606363),JOLY CHRISTOPHER (606743),COND,207024.0,NaN,NaN,VEHICULES,Signalement au dépôt,Non Bloquant,NaN,NaN
3,31094,En cours,21/08/2024,07:11,21/08/2024,07:08,NaN,MALKI MOURAD (606363),KHARROUBI WALID (606705),COND,NaN,NaN,NaN,CIRCULATION - REGULATION,Circulation,Présence sur les voies,Ligne retardée,Véhicules
4,31093,En cours,21/08/2024,07:08,21/08/2024,07:06,NaN,MALKI MOURAD (606363),BERANGER JEREMY (606560),COND,NaN,NaN,NaN,PERSONNEL,Comportement,Positif,NaN,disponibilité
5,31092,En cours,21/08/2024,06:59,21/08/2024,06:56,NaN,MALKI MOURAD (606363),AGNUS LAURENT (605597),COND,201366.0,519-519-034 || 34,Gare de Savigny Nandy via Pavillon Bouret,PERSONNEL,Comportement,Positif,NaN,NaN
6,31091,En cours,21/08/2024,06:56,21/08/2024,06:44,NaN,MALKI MOURAD (606363),AVRIL GEORGES (606543),COND,203029.0,519-519-034 || 34,Gare de Savigny Nandy via Pavillon Bouret,PERSONNEL,Comportement,Positif,NaN,NaN
7,31090,En cours,21/08/2024,06:44,21/08/2024,06:24,NaN,MALKI MOURAD (606363),GUIYOULE BRUCE (606774),COND,203029.0,519-519-131 || 32,Gare de Savigny-le-Temple Nandy via Aubépine,PERSONNEL,Absence,Absence - N'a pas prévenu,NaN,NaN
8,31089,En cours,20/08/2024,23:40,20/08/2024,23:38,NaN,BENABBAS ALI (606236),RAJASINGAM KEVIN (606727),COND,201064.0,519-519-051 || 51,NaN,PERSONNEL,Incident pendant le service,Problème personnel,NaN,NaN
9,31088,En cours,20/08/2024,23:37,20/08/2024,23:36,NaN,BENABBAS ALI (606236),RAHERINIAINA JEAN ERIC (606474),COND,201049.0,NaN,NaN,VEHICULES,Signalement en ligne,Non Bloquant,NaN,NaN
10,31087,En cours,20/08/2024,18:03,20/08/2024,17:48,18:40,AROUI FARID (606578),DICKO SEYDOU (12122),COND,NaN,519-519-110 || 53,NaN,PERSONNEL,Comportement,Positif,NaN,"formation, disponibilité"
11,31086,En cours,20/08/2024,17:53,20/08/2024,17:38,NaN,AROUI FARID (606578),KHENNOUCI BELKACEM (606233),COND,201046.0,NaN,NaN,VEHICULES,Signalement en ligne,Non Bloquant,NaN,"Billetique, Pupitre SAE"
12,31085,En cours,20/08/2024,17:04,20/08/2024,16:10,16:24,AROUI FARID (606578),MARIR ABDESSLAM (606572),COND,202030.0,519-519-100 || 100,Gare de Lieusaint Moissy,PERSONNEL,Incident pendant le service,Erreur,Course partielle,Conducteur
13,31084,En cours,20/08/2024,16:05,20/08/2024,15:40,NaN,SLIMANE SULLEIMAN (12090),AGHROU YASSIN (606446),COND,201384.0,519-519-100 || 100,Toutes les directions,VEHICULES,Signalement en ligne,Bloquant,NaN,NaN
14,31083,En cours,20/08/2024,15:08,20/08/2024,14:01,NaN,SLIMANE SULLEIMAN (12090),DEROCHE JACQUES (606308),COND,207025.0,519-519-050 || 50,NaN,VEHICULES,Signalement en ligne,Bloquant,NaN,PMR
15,31081,En cours,20/08/2024,14:01,20/08/2024,13:29,NaN,SLIMANE SULLEIMAN (12090),MARIR ABDESSLAM (606572),COND,201378.0,519-519-100 || 100,Toutes les directions,VEHICULES,Signalement au dépôt,Bloquant,NaN,NaN
16,31080,En cours,20/08/2024,13:29,20/08/2024,13:10,13:25,SLIMANE SULLEIMAN (12090),DELGADO OLIVIER (606268),COND,201067.0,519-519-122 || 21,LIEUSAINT MOISSY GARE RER,CIRCULATION - REGULATION,Régulation,Interventions service interne,NaN,Contrôleurs
17,31082,En cours,20/08/2024,14:45,20/08/2024,13:06,NaN,AROUI FARID (606578),DEROCHE JACQUES (606308),COND,207025.0,519-519-050 || 50,NaN,VEHICULES,Signalement en ligne,Bloquant,"Ligne partielle, Course partielle",PMR
18,31079,En cours,20/08/2024,12:40,20/08/2024,12:38,NaN,AROUI FARID (606578),MATILI MOHAMMED (606157),COND,NaN,519-519-002 || 02,NaN,PERSONNEL,Comportement,Positif,Sans incidence,"disponibilité, formation"
19,31078,En cours,20/08/2024,11:54,20/08/2024,12:24,13:30,SLIMANE SULLEIMAN (12090),BAWALA PRINCE (606781),COND,201047.0,519-519-051 || 51,NaN,PERSONNEL,Comportement,Positif,NaN,disponibilité
20,31077,En cours,20/08/2024,09:22,20/08/2024,08:25,NaN,ZEGHOUDI MOHAMMED (605835),KHATIB MAJED (606874),COND,NaN,NaN,NaN,PERSONNEL,Comportement,Positif,Ligne retardée,formation
21,31076,En cours,20/08/2024,08:25,20/08/2024,08:18,NaN,ZEGHOUDI MOHAMMED (605835),BLAIN ERIC (606315),COND,NaN,NaN,NaN,PERSONNEL,Comportement,Positif,NaN,disponibilité
22,31075,En cours,19/08/2024,19:20,19/08/2024,17:45,NaN,AROUI FARID (606578),CHADET ANAÏS (606583),COND,231005.0,519-519-129 || 23,Gare de Lieusaint Moissy via Mairie,ACCIDENT,Matériel,Collision avec obstacle fixe,NaN,Dégâts véhicule
23,31074,En cours,19/08/2024,18:00,19/08/2024,17:38,NaN,AROUI FARID (606578),ZAMI JEAN-DANIEL (606777),COND,NaN,519-519-050 || 50,NaN,PERSONNEL,Comportement,Inapproprié,Ligne retardée,Discipline
24,31072,En cours,19/08/2024,17:34,19/08/2024,17:33,NaN,AROUI FARID (606578),NaN,NaN,201406.0,NaN,NaN,VEHICULES,Signalement en ligne,Non Bloquant,NaN,Girouette
25,31070,En cours,19/08/2024,17:01,19/08/2024,16:58,NaN,AROUI FARID (606578),GULSEN KEREM (606805),COND,201070.0,NaN,NaN,VEHICULES,Signalement en ligne,Bloquant,Sans incidence,NaN
26,31069,En cours,19/08/2024,16:57,19/08/2024,16:55,NaN,AROUI FARID (606578),MAGHRI MIMOUNE (606622),COND,201398.0,519-519-132 || 31,Gare de Cesson,VEHICULES,Signalement en ligne,Bloquant,Course non-réalisée,NaN
27,31071,En cours,19/08/2024,17:05,19/08/2024,16:05,17:04,AROUI FARID (606578),ATIGUI MOHAMED YCHEM (606430),COND,NaN,519-519-100 || 100,NaN,PERSONNEL,Comportement,Positif,Sans incidence,disponibilité
28,31073,En cours,19/08/2024,17:38,19/08/2024,15:25,NaN,AROUI FARID (606578),BALTYDE LEONCE (606706),COND,NaN,519-519-100 || 100,NaN,CIRCULATION - REGULATION,Circulation,Embouteillages,NaN,NaN
29,31068,En cours,19/08/2024,16:54,19/08/2024,14:20,NaN,AROUI FARID (606578),PALMOT ROHWANNE (606902),COND,NaN,519-519-100 || 100,NaN,PERSONNEL,Retard prise de service,N'a pas prévenu,Sans incidence,NaN
30,31067,En cours,19/08/2024,14:20,19/08/2024,14:16,NaN,AROUI FARID (606578),ATIGUI MOHAMED (606286),COND,NaN,NaN,NaN,PERSONNEL,Comportement,Positif,Sans incidence,disponibilité
31,31066,En cours,19/08/2024,14:15,19/08/2024,12:56,NaN,AROUI FARID (606578),FOUDRIN BRIGITTE (606802),COND,NaN,NaN,NaN,PERSONNEL,Absence,Absence - A prévenu,NaN,NaN
32,31065,En cours,19/08/2024,11:40,19/08/2024,11:26,NaN,ZEGHOUDI MOHAMMED (605835),DALODIERE YOUNES (606764),COND,NaN,NaN,NaN,PERSONNEL,Absence,Absence - A prévenu,NaN,NaN
33,31064,En cours,19/08/2024,11:26,19/08/2024,06:50,NaN,ZEGHOUDI MOHAMMED (605835),CAMARA MALAHA (606094),COND,NaN,NaN,NaN,PERSONNEL,Comportement,Positif,NaN,NaN
34,31063,En cours,19/08/2024,06:50,19/08/2024,06:44,NaN,ZEGHOUDI MOHAMMED (605835),ROUAIGHIA ABDALLAH (606708),COND,NaN,NaN,NaN,PERSONNEL,Incident pendant le service,Erreur,Ligne partielle,Conducteur
35,31062,En cours,19/08/2024,06:30,19/08/2024,06:19,NaN,MALKI MOURAD (606363),BALTYDE LEONCE (606706),COND,201387.0,519-519-100 || 100,NaN,PERSONNEL,Retard prise de service,N'a pas prévenu,NaN,NaN
36,31061,Traité par l'atelier,18/08/2024,19:34,18/08/2024,19:15,19:40,AROUI FARID (606578),BORREGO DOMINGUES CLINT (606553),COND,201398.0,519-519-139 || 33,Gare de Savigny-le-Temple Nandy via Aubépine,VEHICULES,Signalement en ligne,Bloquant,Course non-réalisée,Voyant Rouge
37,31060,En cours,17/08/2024,17:40,17/08/2024,15:16,NaN,N DIAYE ALASSANE (606358),ROBERT DAMIEN (605964),SEDEN,NaN,NaN,NaN,PERSONNEL,Comportement,Positif,NaN,disponibilité
38,31059,En cours,17/08/2024,15:15,17/08/2024,13:51,NaN,N DIAYE ALASSANE (606358),CAUSIN GIANNI (606840),COND,202030.0,NaN,NaN,ACCIDENT,Matériel,Collision avec obstacle fixe,NaN,Dégâts véhicule
39,31058,En cours,17/08/2024,13:51,17/08/2024,13:50,NaN,N DIAYE ALASSANE (606358),KANTE CHECKNA (606780),COND,NaN,NaN,NaN,PERSONNEL,Comportement,Positif,NaN,"formation, Heures supplémentaires, disponibilité"
40,31057,En cours,17/08/2024,13:50,17/08/2024,13:49,NaN,N DIAYE ALASSANE (606358),GULSEN KEREM (606805),COND,NaN,NaN,NaN,PERSONNEL,Comportement,Positif,NaN,"Heures supplémentaires, disponibilité"
41,31056,En cours,17/08/2024,13:49,17/08/2024,13:48,NaN,N DIAYE ALASSANE (606358),ATIGUI MOHAMED YCHEM (606430),COND,NaN,NaN,NaN,PERSONNEL,Comportement,Positif,NaN,"disponibilité, Heures supplémentaires"
42,31055,En cours,17/08/2024,13:47,17/08/2024,11:45,NaN,N DIAYE ALASSANE (606358),BIQUE MELISSA (606376),COND,NaN,NaN,NaN,PERSONNEL,Absence,Absence - N'a pas prévenu,NaN,NaN
43,31054,En cours,17/08/2024,11:01,17/08/2024,09:42,NaN,AROUI FARID (606578),SEYDI ABOUBAKARY (606894),COND,NaN,NaN,NaN,PERSONNEL,Absence,Absence - A prévenu,Sans incidence,NaN
44,31053,En cours,17/08/2024,09:42,17/08/2024,08:43,NaN,AROUI FARID (606578),CAMARA MALAHA (606094),COND,NaN,NaN,NaN,PERSONNEL,Comportement,Positif,NaN,disponibilité
45,31051,En cours,17/08/2024,08:33,17/08/2024,08:24,NaN,AROUI FARID (606578),ARAUJO DA SILVA DANIELLE (606886),COND,NaN,NaN,NaN,PERSONNEL,Absence,Absence - N'a pas prévenu,Sans incidence,NaN
46,31052,En cours,17/08/2024,08:43,17/08/2024,06:58,11:24,AROUI FARID (606578),ZEMMOURI ABDELKRIM (606230),COND,NaN,NaN,NaN,PERSONNEL,Comportement,Positif,Sans incidence,disponibilité
47,31050,En cours,17/08/2024,06:32,17/08/2024,05:15,NaN,AROUI FARID (606578),TOUTOU DJAMEL (606734),COND,NaN,NaN,NaN,PERSONNEL,Comportement,Positif,NaN,disponibilité
48,31049,En cours,17/08/2024,06:06,17/08/2024,05:00,NaN,AROUI FARID (606578),TOUTOU DJAMEL (606734),COND,NaN,519-519-122 || 21,NaN,PERSONNEL,Comportement,Positif,NaN,disponibilité
49,31048,En cours,17/08/2024,06:04,17/08/2024,04:45,NaN,AROUI FARID (606578),KHARROUBI WALID (606705),COND,201065.0,519-519-122 || 21,NaN,VEHICULES,Signalement en ligne,Bloquant,Course non-réalisée,Voyant Rouge

In [6]:
#filename = 'C:/Users/albert-marc.talla/Desktop/test/Taux de régularité DSP - 18092024131617.xlsx'

df1 = pd.read_excel(filename, header=11)

In [7]:
df1.head(55)

,31087,En cours,20/08/2024,18:03,20/08/2024.1,17:48,18:40,AROUI FARID (606578),DICKO SEYDOU (12122),COND,Unnamed: 10,519-519-110 || 53,Unnamed: 12,PERSONNEL,Comportement,Positif,Unnamed: 16,"formation, disponibilité"
0,31086,En cours,20/08/2024,17:53,20/08/2024,17:38,NaN,AROUI FARID (606578),KHENNOUCI BELKACEM (606233),COND,201046.0,NaN,NaN,VEHICULES,Signalement en ligne,Non Bloquant,NaN,"Billetique, Pupitre SAE"
1,31085,En cours,20/08/2024,17:04,20/08/2024,16:10,16:24,AROUI FARID (606578),MARIR ABDESSLAM (606572),COND,202030.0,519-519-100 || 100,Gare de Lieusaint Moissy,PERSONNEL,Incident pendant le service,Erreur,Course partielle,Conducteur
2,31084,En cours,20/08/2024,16:05,20/08/2024,15:40,NaN,SLIMANE SULLEIMAN (12090),AGHROU YASSIN (606446),COND,201384.0,519-519-100 || 100,Toutes les directions,VEHICULES,Signalement en ligne,Bloquant,NaN,NaN
3,31083,En cours,20/08/2024,15:08,20/08/2024,14:01,NaN,SLIMANE SULLEIMAN (12090),DEROCHE JACQUES (606308),COND,207025.0,519-519-050 || 50,NaN,VEHICULES,Signalement en ligne,Bloquant,NaN,PMR
4,31081,En cours,20/08/2024,14:01,20/08/2024,13:29,NaN,SLIMANE SULLEIMAN (12090),MARIR ABDESSLAM (606572),COND,201378.0,519-519-100 || 100,Toutes les directions,VEHICULES,Signalement au dépôt,Bloquant,NaN,NaN
5,31080,En cours,20/08/2024,13:29,20/08/2024,13:10,13:25,SLIMANE SULLEIMAN (12090),DELGADO OLIVIER (606268),COND,201067.0,519-519-122 || 21,LIEUSAINT MOISSY GARE RER,CIRCULATION - REGULATION,Régulation,Interventions service interne,NaN,Contrôleurs
6,31082,En cours,20/08/2024,14:45,20/08/2024,13:06,NaN,AROUI FARID (606578),DEROCHE JACQUES (606308),COND,207025.0,519-519-050 || 50,NaN,VEHICULES,Signalement en ligne,Bloquant,"Ligne partielle, Course partielle",PMR
7,31079,En cours,20/08/2024,12:40,20/08/2024,12:38,NaN,AROUI FARID (606578),MATILI MOHAMMED (606157),COND,NaN,519-519-002 || 02,NaN,PERSONNEL,Comportement,Positif,Sans incidence,"disponibilité, formation"
8,31078,En cours,20/08/2024,11:54,20/08/2024,12:24,13:30,SLIMANE SULLEIMAN (12090),BAWALA PRINCE (606781),COND,201047.0,519-519-051 || 51,NaN,PERSONNEL,Comportement,Positif,NaN,disponibilité
9,31077,En cours,20/08/2024,09:22,20/08/2024,08:25,NaN,ZEGHOUDI MOHAMMED (605835),KHATIB MAJED (606874),COND,NaN,NaN,NaN,PERSONNEL,Comportement,Positif,Ligne retardée,formation
10,31076,En cours,20/08/2024,08:25,20/08/2024,08:18,NaN,ZEGHOUDI MOHAMMED (605835),BLAIN ERIC (606315),COND,NaN,NaN,NaN,PERSONNEL,Comportement,Positif,NaN,disponibilité
11,31075,En cours,19/08/2024,19:20,19/08/2024,17:45,NaN,AROUI FARID (606578),CHADET ANAÏS (606583),COND,231005.0,519-519-129 || 23,Gare de Lieusaint Moissy via Mairie,ACCIDENT,Matériel,Collision avec obstacle fixe,NaN,Dégâts véhicule
12,31074,En cours,19/08/2024,18:00,19/08/2024,17:38,NaN,AROUI FARID (606578),ZAMI JEAN-DANIEL (606777),COND,NaN,519-519-050 || 50,NaN,PERSONNEL,Comportement,Inapproprié,Ligne retardée,Discipline
13,31072,En cours,19/08/2024,17:34,19/08/2024,17:33,NaN,AROUI FARID (606578),NaN,NaN,201406.0,NaN,NaN,VEHICULES,Signalement en ligne,Non Bloquant,NaN,Girouette
14,31070,En cours,19/08/2024,17:01,19/08/2024,16:58,NaN,AROUI FARID (606578),GULSEN KEREM (606805),COND,201070.0,NaN,NaN,VEHICULES,Signalement en ligne,Bloquant,Sans incidence,NaN
15,31069,En cours,19/08/2024,16:57,19/08/2024,16:55,NaN,AROUI FARID (606578),MAGHRI MIMOUNE (606622),COND,201398.0,519-519-132 || 31,Gare de Cesson,VEHICULES,Signalement en ligne,Bloquant,Course non-réalisée,NaN
16,31071,En cours,19/08/2024,17:05,19/08/2024,16:05,17:04,AROUI FARID (606578),ATIGUI MOHAMED YCHEM (606430),COND,NaN,519-519-100 || 100,NaN,PERSONNEL,Comportement,Positif,Sans incidence,disponibilité
17,31073,En cours,19/08/2024,17:38,19/08/2024,15:25,NaN,AROUI FARID (606578),BALTYDE LEONCE (606706),COND,NaN,519-519-100 || 100,NaN,CIRCULATION - REGULATION,Circulation,Embouteillages,NaN,NaN
18,31068,En cours,19/08/2024,16:54,19/08/2024,14:20,NaN,AROUI FARID (606578),PALMOT ROHWANNE (606902),COND,NaN,519-519-100 || 100,NaN,PERSONNEL,Retard prise de service,N'a pas prévenu,Sans incidence,NaN
19,31067,En cours,19/08/2024,14:20,19/08/2024,14:16,NaN,AROUI FARID (606578),ATIGUI MOHAMED (606286),COND,NaN,NaN,NaN,PERSONNEL,Comportement,Positif,Sans incidence,disponibilité
20,31066,En cours,19/08/2024,14:15,19/08/2024,12:56,NaN,AROUI FARID (606578),FOUDRIN BRIGITTE (606802),COND,NaN,NaN,NaN,PERSONNEL,Absence,Absence - A prévenu,NaN,NaN
21,31065,En cours,19/08/2024,11:40,19/08/2024,11:26,NaN,ZEGHOUDI MOHAMMED (605835),DALODIERE YOUNES (606764),COND,NaN,NaN,NaN,PERSONNEL,Absence,Absence - A prévenu,NaN,NaN
22,31064,En cours,19/08/2024,11:26,19/08/2024,06:50,NaN,ZEGHOUDI MOHAMMED (605835),CAMARA MALAHA (606094),COND,NaN,NaN,NaN,PERSONNEL,Comportement,Positif,NaN,NaN
23,31063,En cours,19/08/2024,06:50,19/08/2024,06:44,NaN,ZEGHOUDI MOHAMMED (605835),ROUAIGHIA ABDALLAH (606708),COND,NaN,NaN,NaN,PERSONNEL,Incident pendant le service,Erreur,Ligne partielle,Conducteur
24,31062,En cours,19/08/2024,06:30,19/08/2024,06:19,NaN,MALKI MOURAD (606363),BALTYDE LEONCE (606706),COND,201387.0,519-519-100 || 100,NaN,PERSONNEL,Retard prise de service,N'a pas prévenu,NaN,NaN
25,31061,Traité par l'atelier,18/08/2024,19:34,18/08/2024,19:15,19:40,AROUI FARID (606578),BORREGO DOMINGUES CLINT (606553),COND,201398.0,519-519-139 || 33,Gare de Savigny-le-Temple Nandy via Aubépine,VEHICULES,Signalement en ligne,Bloquant,Course non-réalisée,Voyant Rouge
26,31060,En cours,17/08/2024,17:40,17/08/2024,15:16,NaN,N DIAYE ALASSANE (606358),ROBERT DAMIEN (605964),SEDEN,NaN,NaN,NaN,PERSONNEL,Comportement,Positif,NaN,disponibilité
27,31059,En cours,17/08/2024,15:15,17/08/2024,13:51,NaN,N DIAYE ALASSANE (606358),CAUSIN GIANNI (606840),COND,202030.0,NaN,NaN,ACCIDENT,Matériel,Collision avec obstacle fixe,NaN,Dégâts véhicule
28,31058,En cours,17/08/2024,13:51,17/08/2024,13:50,NaN,N DIAYE ALASSANE (606358),KANTE CHECKNA (606780),COND,NaN,NaN,NaN,PERSONNEL,Comportement,Positif,NaN,"formation, Heures supplémentaires, disponibilité"
29,31057,En cours,17/08/2024,13:50,17/08/2024,13:49,NaN,N DIAYE ALASSANE (606358),GULSEN KEREM (606805),COND,NaN,NaN,NaN,PERSONNEL,Comportement,Positif,NaN,"Heures supplémentaires, disponibilité"
30,31056,En cours,17/08/2024,13:49,17/08/2024,13:48,NaN,N DIAYE ALASSANE (606358),ATIGUI MOHAMED YCHEM (606430),COND,NaN,NaN,NaN,PERSONNEL,Comportement,Positif,NaN,"disponibilité, Heures supplémentaires"
31,31055,En cours,17/08/2024,13:47,17/08/2024,11:45,NaN,N DIAYE ALASSANE (606358),BIQUE MELISSA (606376),COND,NaN,NaN,NaN,PERSONNEL,Absence,Absence - N'a pas prévenu,NaN,NaN
32,31054,En cours,17/08/2024,11:01,17/08/2024,09:42,NaN,AROUI FARID (606578),SEYDI ABOUBAKARY (606894),COND,NaN,NaN,NaN,PERSONNEL,Absence,Absence - A prévenu,Sans incidence,NaN
33,31053,En cours,17/08/2024,09:42,17/08/2024,08:43,NaN,AROUI FARID (606578),CAMARA MALAHA (606094),COND,NaN,NaN,NaN,PERSONNEL,Comportement,Positif,NaN,disponibilité
34,31051,En cours,17/08/2024,08:33,17/08/2024,08:24,NaN,AROUI FARID (606578),ARAUJO DA SILVA DANIELLE (606886),COND,NaN,NaN,NaN,PERSONNEL,Absence,Absence - N'a pas prévenu,Sans incidence,NaN
35,31052,En cours,17/08/2024,08:43,17/08/2024,06:58,11:24,AROUI FARID (606578),ZEMMOURI ABDELKRIM (606230),COND,NaN,NaN,NaN,PERSONNEL,Comportement,Positif,Sans incidence,disponibilité
36,31050,En cours,17/08/2024,06:32,17/08/2024,05:15,NaN,AROUI FARID (606578),TOUTOU DJAMEL (606734),COND,NaN,NaN,NaN,PERSONNEL,Comportement,Positif,NaN,disponibilité
37,31049,En cours,17/08/2024,06:06,17/08/2024,05:00,NaN,AROUI FARID (606578),TOUTOU DJAMEL (606734),COND,NaN,519-519-122 || 21,NaN,PERSONNEL,Comportement,Positif,NaN,disponibilité
38,31048,En cours,17/08/2024,06:04,17/08/2024,04:45,NaN,AROUI FARID (606578),KHARROUBI WALID (606705),COND,201065.0,519-519-122 || 21,NaN,VEHICULES,Signalement en ligne,Bloquant,Course non-réalisée,Voyant Rouge
39,31047,En cours,16/08/2024,22:18,16/08/2024,22:12,NaN,BENABBAS ALI (606236),ASSOU MOHAMED (12036),COND,2405.0,519-519-127 || 24,Gare de Lieusaint Moissy,ACCIDENT,Corporel et matériel,Collision avec obstacle fixe,NaN,"Voyageur, Dégâts véhicule"
40,31046,En cours,16/08/2024,17:35,16/08/2024,15:40,NaN,SLIMANE SULLEIMAN (12090),SLIMANE SULLEIMAN (12090),COND,231011.0,NaN,NaN,VEHICULES,Signalement en ligne,Non Bloquant,NaN,NaN
41,31045,En cours,16/08/2024,15:39,16/08/2024,15:38,NaN,SLIMANE SULLEIMAN (12090),BENSADOK SOFIANE (606761),COND,203030.0,NaN,NaN,VEHICULES,Signalement au dépôt,Bloquant,NaN,NaN
42,31044,Refusé par l'atelier,16/08/2024,14:43,16/08/2024,14:22,NaN,AROUI FARID (606578),AKNOUCHE A ABDENOUR (606856),COND,201368.0,519-519-132 || 31,Gare de Cesson,VEHICULES,Signalement au dépôt,Bloquant,Ligne partielle,NaN
43,31043,En cours,16/08/2024,14:21,16/08/2024,14:20,NaN,AROUI FARID (606578),ATIGUI MOHAMED (606286),COND,NaN,NaN,NaN,PERSONNEL,Comportement,Positif,NaN,"disponibilité, Heures supplémentaires"
44,31042,En cours,16/08/2024,14:20,16/08/2024,14:12,NaN,AROUI FARID (606578),ATIGUI MOHAMED YCHEM (606430),COND,NaN,NaN,NaN,PERSONNEL,Comportement,Positif,Sans incidence,disponibilité
45,31041,Refusé par l'atelier,16/08/2024,14:12,16/08/2024,14:09,NaN,AROUI FARID (606578),AKNOUCHE A ABDENOUR (606856),COND,201408.0,NaN,NaN,VEHICULES,Signalement au dépôt,Non Bloquant,NaN,"Pupitre SAE, Billetique"
46,31040,En cours,16/08/2024,14:09,16/08/2024,12:17,NaN,AROUI FARID (606578),SEYDI ABOUBAKARY (606894),COND,NaN,NaN,NaN,PERSONNEL,Absence,Absence - A prévenu,Sans incidence,NaN
47,31038,En cours,16/08/2024,11:21,16/08/2024,11:08,11:28,AROUI FARID (606578),DE SOUSA ESTEVE (607993),NaN,NaN,519-519-122 || 21,Gare de Combs-La-Ville Quincy,CIRCULATION - REGULATION,Régulation,Interventions service interne,Ligne retardée,Contrôleurs
48,31039,En cours,16/08/2024,11:24,16/08/2024,09:34,13:04,AROUI FARID (606578),CAMARA MALAHA (606094),COND,NaN,519-519-077 || CITA,NaN,PERSONNEL,Comportement,Positif,Sans incidence,"Heures supplémentaires, disponibilité"
49,31033,En cours,15/08/2024,16:43,16/08/2024,09:30,13:03,SLIMANE SULLEIMAN (12090),CAMARA MALAHA (606094),COND,201050.0,519-519-077 || CITA,Toutes les directions,PERSONNEL,Comportement,Positif,NaN,"Heures supplémentaires, disponibilité"
50,31032,En cours,15/08/2024,16:38,16/08/2024,09:24,13:03,SLIMANE SULLEIMAN (12090),DOUCOURE SOUAIBOU (606904),COND,201050.0,519-519-077 || CITA,Toutes les directions,PERSONNEL,Absence,Absence - A prévenu,NaN,NaN
51,31036,Refusé par l'atelier,16/08/2024,06:45,16/08/2024,06:39,NaN,ALDONER JOACHIM (606503),CORNU JEROME (605653),COND,201411.0,519-519-034 || 34,Gare de Savigny Nandy via Pavillon Bouret,VEHICULES,Signalement en ligne,Bloquant,Course non-réalisée,Voyant Rouge
52,31035,En cours,16/08/2024,05:59,16/08/2024,05:55,NaN,MALKI MOURAD (606363),FOURTI SOFYAN (606866),COND,207011.0,519-519-050 || 50,Gare d'Evry Courcouronnes,PERSONNEL,Absence,Absence - N'a pas prévenu,Sans incidence,NaN
53,31037,En cours,16/08/2024,10:41,16/08/2024,05:00,NaN,AROUI FARID (606578),KANTE CHECKNA (606780),COND,207011.0,519-519-050 || 50,NaN,PERSONNEL,Comportement,Positif,NaN,"disponibilité, Heures supplémentaires"
54,31034,Refusé par l'atelier,15/08/2024,17:17,15/08/2024,17:15,17:43,SLIMANE SULLEIMAN (12090),MAHMOUD MEHDI (606742),COND,201412.0,519-519-139 || 33,Gare de Savigny-le-Temple Nandy via Aubépine,VEHICULES,Signalement en ligne,Bloquant,Course non-réalisée,Voyant Rouge

In [7]:
df1.columns

Index(['Transporteur', 'Semaine 2024 35', 'Unnamed: 2', 'Unnamed: 3',
       'Unnamed: 4', 'Semaine 2024 36', 'Unnamed: 6', 'Unnamed: 7',
       'Unnamed: 8', 'Semaine 2024 37', 'Unnamed: 10', 'Unnamed: 11',
       'Unnamed: 12', 'Semaine 2024 38', 'Unnamed: 14', 'Unnamed: 15',
       'Unnamed: 16', 'Totaux', 'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20'],
      dtype='object')

In [28]:
df1_S1=df1[['Transporteur', 'Semaine 2024 35', 'Unnamed: 2', 'Unnamed: 3',
       'Unnamed: 4']]

df1_S2=df1[['Semaine 2024 36','Unnamed: 6', 'Unnamed: 7',
       'Unnamed: 8']]

df1_S3 =df1[['Semaine 2024 37', 'Unnamed: 10', 'Unnamed: 11',
       'Unnamed: 12']]

In [29]:
df1_S1.head()

     Transporteur Semaine 2024 35    Unnamed: 2    Unnamed: 3 Unnamed: 4
0           Ligne   Tx conformite  Tx SI avance  Tx SI retard      Tx SI
1  DSP19 - SENART        0.931777      0.013608        0.0058   0.019408
2            TZN1        0.926288      0.015576      0.002528   0.018104
3              01             NaN           NaN           NaN        NaN
4              02        0.947664      0.015888             0   0.015888

In [30]:


date_S1=df1_S1.columns.to_list()[1]

df1_S1 = df1_S1.copy()
df1_S1['Date'] = date_S1

#df1_S1['Date']= date_S1
#type(date_S1)

In [31]:
df1_S1.head(2)

,Transporteur,Semaine 2024 35,Unnamed: 2,Unnamed: 3,Unnamed: 4,Date
0,Ligne,Tx conformite,Tx SI avance,Tx SI retard,Tx SI,Semaine 2024 35
1,DSP19 - SENART,0.931777,0.013608,0.0058,0.019408,Semaine 2024 35

In [32]:
df1_S1.columns=df1_S1.iloc[0]

In [33]:
df1_S1.head(2)

,Ligne,Tx conformite,Tx SI avance,Tx SI retard,Tx SI,Semaine 2024 35
0,Ligne,Tx conformite,Tx SI avance,Tx SI retard,Tx SI,Semaine 2024 35
1,DSP19 - SENART,0.931777,0.013608,0.0058,0.019408,Semaine 2024 35

In [34]:
df1_S1=df1_S1[2:]

In [35]:
df1_S1.head(2)

0 Ligne Tx conformite Tx SI avance Tx SI retard     Tx SI  Semaine 2024 35
2  TZN1      0.926288     0.015576     0.002528  0.018104  Semaine 2024 35
3    01           NaN          NaN          NaN       NaN  Semaine 2024 35

In [36]:
type(df1_S1)
#df1_S1=df1_S1.reset_index(drop=True)

pandas.core.frame.DataFrame

In [102]:
df1_S1=df1_S1.reset_index(drop=True)

In [103]:
df1_S1.head(2)

0 Ligne Tx conformite Tx SI avance Tx SI retard     Tx SI  Semaine 2024 35
0  TZN1      0.926288     0.015576     0.002528  0.018104  Semaine 2024 35
1    01           NaN          NaN          NaN       NaN  Semaine 2024 35

In [104]:
df1_S1.rename(columns={'Semaine 2024 35':'Date'})

,Ligne,Tx conformite,Tx SI avance,Tx SI retard,Tx SI,Date
0,TZN1,0.926288,0.015576,0.002528,0.018104,Semaine 2024 35
1,01,NaN,NaN,NaN,NaN,Semaine 2024 35
2,02,0.947664,0.015888,0,0.015888,Semaine 2024 35
3,03,0.980887,0.009939,0.000765,0.010703,Semaine 2024 35
4,04,0.952328,0.008869,0.00388,0.012749,Semaine 2024 35
5,05,NaN,NaN,NaN,NaN,Semaine 2024 35
6,11,0.959989,0.008165,0.001633,0.009799,Semaine 2024 35
7,12,0.966903,0.013855,0.004002,0.017857,Semaine 2024 35
8,13,0.979186,0.008326,0.000308,0.008634,Semaine 2024 35
9,21,0.925339,0.011312,0.004309,0.015622,Semaine 2024 35
10,22,0.912613,0.009079,0.012322,0.021401,Semaine 2024 35
11,23,0.898671,0.036545,0.016196,0.052741,Semaine 2024 35
12,24,0.9416,0.007964,0.003792,0.011756,Semaine 2024 35
13,25,0.923048,0.008299,0.026405,0.034704,Semaine 2024 35
14,26,0.936541,0.026499,0.006974,0.033473,Semaine 2024 35
15,27,0.958333,0.014583,0.010417,0.025,Semaine 2024 35
16,31,0.954018,0.004537,0.001769,0.006305,Semaine 2024 35
17,32,0.965986,0.008098,0.000648,0.008746,Semaine 2024 35
18,33,0.943556,0.007526,0.002822,0.010348,Semaine 2024 35
19,34,0.977907,0.008337,0,0.008337,Semaine 2024 35
20,35,0.967647,0.017647,0.005882,0.023529,Semaine 2024 35
21,36,0.952116,0.021521,0.007174,0.028694,Semaine 2024 35
22,37,0.971079,0.014461,0.001112,0.015573,Semaine 2024 35
23,41,0.978846,0.015385,0.000962,0.016346,Semaine 2024 35
24,42,0.953435,0.022392,0.003053,0.025445,Semaine 2024 35
25,43,0.966056,0.014866,0.000496,0.015362,Semaine 2024 35
26,50,0.838578,0.031886,0.005664,0.03755,Semaine 2024 35
27,51,0.923581,0.011421,0.008062,0.019483,Semaine 2024 35
28,52,NaN,NaN,NaN,NaN,Semaine 2024 35
29,53,0.919954,0.005568,0.016241,0.02181,Semaine 2024 35
30,54,0.697183,0.274648,0.003521,0.278169,Semaine 2024 35
31,55,0.731602,0.047619,0.073593,0.121212,Semaine 2024 35
32,61B,NaN,NaN,NaN,NaN,Semaine 2024 35
33,61A,NaN,NaN,NaN,NaN,Semaine 2024 35
34,62B,NaN,NaN,NaN,NaN,Semaine 2024 35
35,62A,NaN,NaN,NaN,NaN,Semaine 2024 35
36,62C,NaN,NaN,NaN,NaN,Semaine 2024 35
37,63,NaN,NaN,NaN,NaN,Semaine 2024 35
38,64,NaN,NaN,NaN,NaN,Semaine 2024 35
39,CPSF,0.930016,0.032659,0.012442,0.045101,Semaine 2024 35
40,CITA,0.845931,0.010103,0.022451,0.032554,Semaine 2024 35
41,Somme finale,0.931777,0.013608,0.0058,0.019408,Semaine 2024 35

In [105]:
print(df1_S1.columns)

print(df1_S1.head(2))

Index(['Ligne', 'Tx conformite', 'Tx SI avance', 'Tx SI retard', 'Tx SI',
       'Semaine 2024 35'],
      dtype='object', name=0)
0 Ligne Tx conformite Tx SI avance Tx SI retard     Tx SI  Semaine 2024 35
0  TZN1      0.926288     0.015576     0.002528  0.018104  Semaine 2024 35
1    01           NaN          NaN          NaN       NaN  Semaine 2024 35

In [41]:
df = pd.read_excel(filename, header=11)
df.columns

Index(['Transporteur', 'Semaine 2024 35', 'Unnamed: 2', 'Unnamed: 3',
       'Unnamed: 4', 'Semaine 2024 36', 'Unnamed: 6', 'Unnamed: 7',
       'Unnamed: 8', 'Semaine 2024 37', 'Unnamed: 10', 'Unnamed: 11',
       'Unnamed: 12', 'Semaine 2024 38', 'Unnamed: 14', 'Unnamed: 15',
       'Unnamed: 16', 'Totaux', 'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20'],
      dtype='object')

In [42]:
# Extraire les colonnes qui contiennent le mot 'Semaine'
colonnes_semaines = [col for col in df.columns if 'Semaine' in col]

# Afficher les colonnes correspondantes
print(colonnes_semaines)

['Semaine 2024 35', 'Semaine 2024 36', 'Semaine 2024 37', 'Semaine 2024 38']

In [43]:
# Fonction pour récupérer les paires start_week et end_week
def get_week_intervals(df):
    # Récupérer les colonnes contenant 'Semaine'
    week_columns = [col for col in df.columns if 'Semaine' in col]
    
    # Créer une liste pour stocker les paires (start_week, end_week)
    intervals = []

    for i in range(len(week_columns) - 1):
        start_week = week_columns[i]
        end_week = week_columns[i + 1]
        intervals.append((start_week, end_week))
    
    return intervals

In [44]:
# Récupérer les paires de semaines
week_intervals = get_week_intervals(df)

# Affichage des intervalles (start_week, end_week)
print(week_intervals)

[('Semaine 2024 35', 'Semaine 2024 36'), ('Semaine 2024 36', 'Semaine 2024 37'), ('Semaine 2024 37', 'Semaine 2024 38')]

In [49]:
# Fonction pour récupérer les colonnes entre deux semaines, sans inclure la colonne de fin
def get_columns_between_weeks_exclusive(df, start_week, end_week):
    # Initialisation de la liste des colonnes à inclure
    selected_columns = []
    include = False

    for col in df.columns:
        # Vérification si on doit commencer à inclure les colonnes
        if start_week in col:
            include = True
        # Ajout des colonnes tant qu'on est dans l'intervalle
        if include:
            # Arrêter d'ajouter les colonnes dès que la colonne de fin est atteinte
            if end_week in col:
                break
            selected_columns.append(col)
    
    return selected_columns

In [45]:
# Récupérer les paires de semaines
week_intervals

[('Semaine 2024 35', 'Semaine 2024 36'),
 ('Semaine 2024 36', 'Semaine 2024 37'),
 ('Semaine 2024 37', 'Semaine 2024 38')]

In [46]:
week_intervals[0]

('Semaine 2024 35', 'Semaine 2024 36')

In [47]:
week_intervals[0][0]

'Semaine 2024 35'

In [51]:
# Exemple d'utilisation
start_week = week_intervals[0][0]
end_week = week_intervals[0][1]

# Récupérer les colonnes entre deux semaines, sans inclure la colonne de fin
first_week_interval_columns = get_columns_between_weeks_exclusive(df, start_week, end_week)

# Affichage des colonnes sélectionnées
print(first_week_interval_columns)

['Semaine 2024 35', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4']

In [52]:
# Récupérer les paires de semaines
week_intervals = get_week_intervals(df)

# Initialiser un dictionnaire pour stocker les colonnes par intervalle
columns_by_interval = {}

# Boucle sur chaque intervalle (start_week, end_week) pour récupérer les colonnes
for start_week, end_week in week_intervals:
    # Récupérer les colonnes pour cet intervalle spécifique
    interval_columns = get_columns_between_weeks_exclusive(df, start_week, end_week)
    # Stocker le résultat dans le dictionnaire avec l'intervalle comme clé
    columns_by_interval[(start_week, end_week)] = interval_columns

# Afficher les colonnes pour chaque intervalle
for interval, columns in columns_by_interval.items():
    print(f"Intervalle {interval}: {columns}")

Intervalle ('Semaine 2024 35', 'Semaine 2024 36'): ['Semaine 2024 35', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4']
Intervalle ('Semaine 2024 36', 'Semaine 2024 37'): ['Semaine 2024 36', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8']
Intervalle ('Semaine 2024 37', 'Semaine 2024 38'): ['Semaine 2024 37', 'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12']

In [53]:
# Fonction pour récupérer les paires start_week et end_week, incluant la dernière semaine si non suivie
def get_week_intervals(df):
    week_columns = [col for col in df.columns if 'Semaine' in col]
    intervals = []
    for i in range(len(week_columns) - 1):
        start_week = week_columns[i]
        end_week = week_columns[i + 1]
        intervals.append((start_week, end_week))
    # Ajouter la dernière semaine seule si elle n'a pas d'intervalle suivant
    if len(week_columns) > 0:
        intervals.append((week_columns[-1], None))
    return intervals

# Fonction pour récupérer les colonnes entre deux semaines, incluant le cas où end_week est None
def get_columns_between_weeks_exclusive(df, start_week, end_week):
    selected_columns = []
    include = False
    for col in df.columns:
        if start_week in col:
            include = True
        if include:
            # Si end_week est None, inclure toutes les colonnes restantes
            if end_week is None:
                selected_columns.append(col)
            # Sinon, arrêter l'inclusion avant d'atteindre end_week
            elif end_week in col:
                break
            else:
                selected_columns.append(col)
    return selected_columns

# Récupérer les paires de semaines
week_intervals = get_week_intervals(df)

# Initialiser un dictionnaire pour stocker les colonnes par intervalle
columns_by_interval = {}

# Boucle sur chaque intervalle (start_week, end_week) pour récupérer les colonnes
for start_week, end_week in week_intervals:
    # Récupérer les colonnes pour cet intervalle spécifique
    interval_columns = get_columns_between_weeks_exclusive(df, start_week, end_week)
    # Stocker le résultat dans le dictionnaire avec l'intervalle comme clé
    columns_by_interval[(start_week, end_week)] = interval_columns

# Afficher les colonnes pour chaque intervalle
for interval, columns in columns_by_interval.items():
    print(f"Intervalle {interval}: {columns}")

Intervalle ('Semaine 2024 35', 'Semaine 2024 36'): ['Semaine 2024 35', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4']
Intervalle ('Semaine 2024 36', 'Semaine 2024 37'): ['Semaine 2024 36', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8']
Intervalle ('Semaine 2024 37', 'Semaine 2024 38'): ['Semaine 2024 37', 'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12']
Intervalle ('Semaine 2024 38', None): ['Semaine 2024 38', 'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Totaux', 'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20']

In [56]:
columns_by_interval

{('Semaine 2024 35', 'Semaine 2024 36'): ['Semaine 2024 35',
  'Unnamed: 2',
  'Unnamed: 3',
  'Unnamed: 4'],
 ('Semaine 2024 36', 'Semaine 2024 37'): ['Semaine 2024 36',
  'Unnamed: 6',
  'Unnamed: 7',
  'Unnamed: 8'],
 ('Semaine 2024 37', 'Semaine 2024 38'): ['Semaine 2024 37',
  'Unnamed: 10',
  'Unnamed: 11',
  'Unnamed: 12'],
 ('Semaine 2024 38', None): ['Semaine 2024 38',
  'Unnamed: 14',
  'Unnamed: 15',
  'Unnamed: 16',
  'Totaux',
  'Unnamed: 18',
  'Unnamed: 19',
  'Unnamed: 20']}

In [58]:
#columns

In [60]:
# Récupérer le premier intervalle
first_interval = list(columns_by_interval.keys())[0]

# Récupérer les colonnes correspondant au premier intervalle
first_interval_columns = columns_by_interval[first_interval]

# Créer le DataFrame S1 en sélectionnant les colonnes dans df1
S1 = df[first_interval_columns]

# Afficher le DataFrame S1
print("DataFrame S1 basé sur le premier intervalle :")
display(S1)

DataFrame S1 basé sur le premier intervalle :

   Semaine 2024 35    Unnamed: 2    Unnamed: 3 Unnamed: 4
0    Tx conformite  Tx SI avance  Tx SI retard      Tx SI
1         0.931777      0.013608        0.0058   0.019408
2         0.926288      0.015576      0.002528   0.018104
3              NaN           NaN           NaN        NaN
4         0.947664      0.015888             0   0.015888
5         0.980887      0.009939      0.000765   0.010703
6         0.952328      0.008869       0.00388   0.012749
7              NaN           NaN           NaN        NaN
8         0.959989      0.008165      0.001633   0.009799
9         0.966903      0.013855      0.004002   0.017857
10        0.979186      0.008326      0.000308   0.008634
11        0.925339      0.011312      0.004309   0.015622
12        0.912613      0.009079      0.012322   0.021401
13        0.898671      0.036545      0.016196   0.052741
14          0.9416      0.007964      0.003792   0.011756
15        0.923048      0.008299      0.026405   0.034704
16        0.936541      0.026499      0.006974   0.033473
17        0.958333      0.014583      0.010417      0.025
18        0.954018      0.004537      0.001769   0.006305
19        0.965986      0.008098      0.000648   0.008746
20        0.943556      0.007526      0.002822   0.010348
21        0.977907      0.008337             0   0.008337
22        0.967647      0.017647      0.005882   0.023529
23        0.952116      0.021521      0.007174   0.028694
24        0.971079      0.014461      0.001112   0.015573
25        0.978846      0.015385      0.000962   0.016346
26        0.953435      0.022392      0.003053   0.025445
27        0.966056      0.014866      0.000496   0.015362
28        0.838578      0.031886      0.005664    0.03755
29        0.923581      0.011421      0.008062   0.019483
30             NaN           NaN           NaN        NaN
31        0.919954      0.005568      0.016241    0.02181
32        0.697183      0.274648      0.003521   0.278169
33        0.731602      0.047619      0.073593   0.121212
34             NaN           NaN           NaN        NaN
35             NaN           NaN           NaN        NaN
36             NaN           NaN           NaN        NaN
37             NaN           NaN           NaN        NaN
38             NaN           NaN           NaN        NaN
39             NaN           NaN           NaN        NaN
40             NaN           NaN           NaN        NaN
41        0.930016      0.032659      0.012442   0.045101
42        0.845931      0.010103      0.022451   0.032554
43        0.931777      0.013608        0.0058   0.019408

In [63]:
# Dictionnaire pour stocker les DataFrames par intervalle
dataframes_by_interval = {}

# Boucle sur chaque intervalle dans columns_by_interval
for idx, (interval, columns) in enumerate(columns_by_interval.items()):
    # Créer un DataFrame pour chaque intervalle
    df_interval = df[columns]
    # Nommer le DataFrame (par exemple, S1, S2, S3, etc.)
    dataframe_name = f"S{idx + 1}"
    # Stocker le DataFrame dans le dictionnaire
    dataframes_by_interval[dataframe_name] = df_interval
    # Afficher le DataFrame
    print(f"DataFrame {dataframe_name} basé sur l'intervalle {interval}:")
    display(df_interval.head(2))
    print("\n")

# Accéder aux DataFrames dans le dictionnaire
# Par exemple, accéder à S1
S1 = dataframes_by_interval['S1']

DataFrame S1 basé sur l'intervalle ('Semaine 2024 35', 'Semaine 2024 36'):

  Semaine 2024 35    Unnamed: 2    Unnamed: 3 Unnamed: 4
0   Tx conformite  Tx SI avance  Tx SI retard      Tx SI
1        0.931777      0.013608        0.0058   0.019408

DataFrame S2 basé sur l'intervalle ('Semaine 2024 36', 'Semaine 2024 37'):

  Semaine 2024 36    Unnamed: 6    Unnamed: 7 Unnamed: 8
0   Tx conformite  Tx SI avance  Tx SI retard      Tx SI
1        0.921553      0.013807      0.008999   0.022806

DataFrame S3 basé sur l'intervalle ('Semaine 2024 37', 'Semaine 2024 38'):

  Semaine 2024 37   Unnamed: 10   Unnamed: 11 Unnamed: 12
0   Tx conformite  Tx SI avance  Tx SI retard       Tx SI
1        0.920352      0.017158      0.007891    0.025049

DataFrame S4 basé sur l'intervalle ('Semaine 2024 38', None):

,Semaine 2024 38,Unnamed: 14,Unnamed: 15,Unnamed: 16,Totaux,Unnamed: 18,Unnamed: 19,Unnamed: 20
0,Tx conformite,Tx SI avance,Tx SI retard,Tx SI,Tx conformite,Tx SI avance,Tx SI retard,Tx SI
1,0.930056,0.016524,0.00765,0.024174,0.924892,0.015167,0.007641,0.022808

In [64]:
# Dictionnaire pour stocker les DataFrames par intervalle
dataframes_by_interval = {}

# Boucle sur chaque intervalle dans columns_by_interval
for idx, (interval, columns) in enumerate(columns_by_interval.items()):
    # Créer un DataFrame pour chaque intervalle
    df_interval = df[columns].copy()
    
    # Récupérer le nom de la colonne de date
    date_S1 = df_interval.columns.to_list()[0]  # Prendre le nom de la première colonne
    
    # Ajouter la colonne 'Date' au DataFrame
    df_interval['Date'] = date_S1
    
    # Renommer les colonnes avec la première ligne
    df_interval.columns = df_interval.iloc[0]
    
    # Supprimer les deux premières lignes et réinitialiser l'index
    df_interval = df_interval[2:].reset_index(drop=True)
    
    # Nommer le DataFrame (par exemple, S1, S2, S3, etc.)
    dataframe_name = f"S{idx + 1}"
    
    # Stocker le DataFrame transformé dans le dictionnaire
    dataframes_by_interval[dataframe_name] = df_interval
    
    # Afficher le DataFrame transformé
    print(f"DataFrame {dataframe_name} transformé :")
    display(df_interval.head(2))
    print("\n")

# Accéder aux DataFrames transformés dans le dictionnaire
# Par exemple, accéder à S1
S1 = dataframes_by_interval['S1']

DataFrame S1 transformé :

0 Tx conformite Tx SI avance Tx SI retard     Tx SI  Semaine 2024 35
0      0.926288     0.015576     0.002528  0.018104  Semaine 2024 35
1           NaN          NaN          NaN       NaN  Semaine 2024 35

DataFrame S2 transformé :

0 Tx conformite Tx SI avance Tx SI retard     Tx SI  Semaine 2024 36
0      0.920407     0.017316     0.005316  0.022632  Semaine 2024 36
1      0.766323     0.041237     0.013746  0.054983  Semaine 2024 36

DataFrame S3 transformé :

0 Tx conformite Tx SI avance Tx SI retard     Tx SI  Semaine 2024 37
0      0.923497     0.019879     0.002187  0.022066  Semaine 2024 37
1        0.7022     0.106599     0.032149  0.138748  Semaine 2024 37

DataFrame S4 transformé :

,Tx conformite,Tx SI avance,Tx SI retard,Tx SI,Tx conformite,Tx SI avance,Tx SI retard,Tx SI,Semaine 2024 38
0,0.943673,0.019833,0.000793,0.020627,0.925623,0.017856,0.003004,0.02086,Semaine 2024 38
1,0.693182,0.022727,0.007576,0.030303,0.719428,0.076923,0.023669,0.100592,Semaine 2024 38

In [66]:
# Dictionnaire pour stocker les DataFrames par intervalle
dataframes_by_interval = {}

# Boucle sur chaque intervalle dans columns_by_interval
for idx, (interval, columns) in enumerate(columns_by_interval.items()):
    # Créer un DataFrame pour chaque intervalle
    df_interval = df[columns].copy()
    
    # Récupérer le nom de la colonne de date
    date_S1 = df_interval.columns.to_list()[0]  # Prendre le nom de la première colonne
    
    # Ajouter la colonne 'Date' au DataFrame
    df_interval['Date'] = date_S1
    
    # Renommer les colonnes avec la première ligne
    df_interval.columns = df_interval.iloc[0]
    
    # Supprimer les deux premières lignes et réinitialiser l'index
    df_interval = df_interval[2:].reset_index(drop=True)
    
    # Renommer la colonne 'Semaine XXXX XX' en 'Date'
    df_interval.rename(columns={date_S1: 'Date'}, inplace=True)
    
    # Nommer le DataFrame (par exemple, S1, S2, S3, etc.)
    dataframe_name = f"S{idx + 1}"
    
    # Stocker le DataFrame transformé dans le dictionnaire
    dataframes_by_interval[dataframe_name] = df_interval
    
    # Afficher le DataFrame transformé
    print(f"DataFrame {dataframe_name} transformé :")
    display(df_interval.head(2))
    print("\n")

# Accéder aux DataFrames transformés dans le dictionnaire
# Par exemple, accéder à S1
S1 = dataframes_by_interval['S1']

DataFrame S1 transformé :

0 Tx conformite Tx SI avance Tx SI retard     Tx SI             Date
0      0.926288     0.015576     0.002528  0.018104  Semaine 2024 35
1           NaN          NaN          NaN       NaN  Semaine 2024 35

DataFrame S2 transformé :

0 Tx conformite Tx SI avance Tx SI retard     Tx SI             Date
0      0.920407     0.017316     0.005316  0.022632  Semaine 2024 36
1      0.766323     0.041237     0.013746  0.054983  Semaine 2024 36

DataFrame S3 transformé :

0 Tx conformite Tx SI avance Tx SI retard     Tx SI             Date
0      0.923497     0.019879     0.002187  0.022066  Semaine 2024 37
1        0.7022     0.106599     0.032149  0.138748  Semaine 2024 37

DataFrame S4 transformé :

,Tx conformite,Tx SI avance,Tx SI retard,Tx SI,Tx conformite,Tx SI avance,Tx SI retard,Tx SI,Date
0,0.943673,0.019833,0.000793,0.020627,0.925623,0.017856,0.003004,0.02086,Semaine 2024 38
1,0.693182,0.022727,0.007576,0.030303,0.719428,0.076923,0.023669,0.100592,Semaine 2024 38

In [79]:
# Dictionnaire pour stocker les DataFrames par intervalle
dataframes_by_interval = {}

# Boucle sur chaque intervalle dans columns_by_interval
for idx, (interval, columns) in enumerate(columns_by_interval.items()):
    # Si c'est le dernier intervalle, exclure les colonnes à partir de 'Totaux'
    if idx == len(columns_by_interval) - 1:
        # Trouver l'index de la colonne 'Totaux'
        if 'Totaux' in columns:
            total_index = columns.index('Totaux')
            # Exclure toutes les colonnes à partir de 'Totaux' inclusivement
            columns = columns[:total_index]
    
    # Créer un DataFrame pour chaque intervalle
    df_interval = df[columns].copy()
    
    # Récupérer le nom de la colonne de date
    date_S1 = df_interval.columns.to_list()[0]  # Prendre le nom de la première colonne
    
    # Ajouter la colonne 'Date' au DataFrame
    df_interval['Date'] = date_S1
    
    # Renommer les colonnes avec la première ligne
    df_interval.columns = df_interval.iloc[0]
    
    # Supprimer les deux premières lignes et réinitialiser l'index
    df_interval = df_interval[2:].reset_index(drop=True)
    
    # Renommer la colonne 'Semaine XXXX XX' en 'Date'
    df_interval.rename(columns={date_S1: 'Date'}, inplace=True)
    
    # Nommer le DataFrame (par exemple, S1, S2, S3, etc.)
    dataframe_name = f"S{idx + 1}"
    
    # Stocker le DataFrame transformé dans le dictionnaire
    dataframes_by_interval[dataframe_name] = df_interval
    
    # Afficher le DataFrame transformé
    print(f"DataFrame {dataframe_name} transformé :")
    display(df_interval.tail(5))
    print("\n")

# Accéder aux DataFrames transformés dans le dictionnaire
# Par exemple, accéder à S1
S1 = dataframes_by_interval['S1']

DataFrame S1 transformé :

0  Tx conformite Tx SI avance Tx SI retard     Tx SI             Date
37           NaN          NaN          NaN       NaN  Semaine 2024 35
38           NaN          NaN          NaN       NaN  Semaine 2024 35
39      0.930016     0.032659     0.012442  0.045101  Semaine 2024 35
40      0.845931     0.010103     0.022451  0.032554  Semaine 2024 35
41      0.931777     0.013608       0.0058  0.019408  Semaine 2024 35

DataFrame S2 transformé :

0  Tx conformite Tx SI avance Tx SI retard     Tx SI             Date
37      0.940196     0.007843     0.005882  0.013725  Semaine 2024 36
38        0.9175         0.01         0.01      0.02  Semaine 2024 36
39      0.952496     0.032206            0  0.032206  Semaine 2024 36
40      0.855589     0.009149     0.006677  0.015826  Semaine 2024 36
41      0.921553     0.013807     0.008999  0.022806  Semaine 2024 36

DataFrame S3 transformé :

0  Tx conformite Tx SI avance Tx SI retard     Tx SI             Date
37         0.933        0.016        0.004      0.02  Semaine 2024 37
38      0.939614     0.014493            0  0.014493  Semaine 2024 37
39      0.953978     0.024961      0.00312  0.028081  Semaine 2024 37
40        0.8503     0.009998     0.005272   0.01527  Semaine 2024 37
41      0.920352     0.017158     0.007891  0.025049  Semaine 2024 37

DataFrame S4 transformé :

0  Tx conformite Tx SI avance Tx SI retard     Tx SI             Date
37      0.897561     0.004878     0.009756  0.014634  Semaine 2024 38
38         0.875     0.029412            0  0.029412  Semaine 2024 38
39      0.981818     0.018182            0  0.018182  Semaine 2024 38
40      0.884149     0.020359     0.004363  0.024721  Semaine 2024 38
41      0.930056     0.016524      0.00765  0.024174  Semaine 2024 38

In [71]:
# Dictionnaire pour stocker les DataFrames par intervalle
dataframes_by_interval = {}

# Liste des colonnes à conserver
columns_to_keep = ['Tx conformite', 'Tx SI avance', 'Tx SI retard', 'Tx SI', 'Date']

# Liste pour stocker les DataFrames filtrés
filtered_dfs = []

# Boucle sur chaque intervalle dans columns_by_interval
for idx, (interval, columns) in enumerate(columns_by_interval.items()):
    # Si c'est le dernier intervalle, exclure les colonnes à partir de 'Totaux'
    if idx == len(columns_by_interval) - 1:
        if 'Totaux' in columns:
            total_index = columns.index('Totaux')
            columns = columns[:total_index]
    
    # Créer un DataFrame pour chaque intervalle
    df_interval = df[columns].copy()
    
    # Récupérer le nom de la colonne de date
    date_S1 = df_interval.columns.to_list()[0]
    
    # Ajouter la colonne 'Date' au DataFrame
    df_interval['Date'] = date_S1
    
    # Renommer les colonnes avec la première ligne
    df_interval.columns = df_interval.iloc[0]
    
    # Supprimer les deux premières lignes et réinitialiser l'index
    df_interval = df_interval[2:].reset_index(drop=True)
    
    # Renommer la colonne 'Semaine XXXX XX' en 'Date'
    df_interval.rename(columns={date_S1: 'Date'}, inplace=True)
    
    # Ajouter les colonnes à conserver depuis df1
    df_interval = df_interval.join(df[columns_to_keep[:-1]])
    
    # Sélectionner uniquement les colonnes à conserver
    df_filtered = df_interval[columns_to_keep]
    
    # Ajouter le DataFrame filtré à la liste
    filtered_dfs.append(df_filtered)

# Concaténer tous les DataFrames filtrés en un seul DataFrame
final_df = pd.concat(filtered_dfs, ignore_index=True)

# Afficher le DataFrame final
print("DataFrame unique après filtrage et concaténation :")
display(final_df)

KeyError: "None of [Index(['Tx conformite', 'Tx SI avance', 'Tx SI retard', 'Tx SI'], dtype='object')] are in the [columns]"

In [73]:
# Dictionnaire pour stocker les DataFrames par intervalle
dataframes_by_interval = {}

# Liste des colonnes à conserver
columns_to_keep = ['Tx conformite', 'Tx SI avance', 'Tx SI retard', 'Tx SI', 'Date']

# Vérifier si toutes les colonnes nécessaires sont dans df1
common_columns = [col for col in columns_to_keep[:-1] if col in df.columns]

# Liste pour stocker les DataFrames filtrés
filtered_dfs = []

# Boucle sur chaque intervalle dans columns_by_interval
for idx, (interval, columns) in enumerate(columns_by_interval.items()):
    # Si c'est le dernier intervalle, exclure les colonnes à partir de 'Totaux'
    if idx == len(columns_by_interval) - 1:
        if 'Totaux' in columns:
            total_index = columns.index('Totaux')
            columns = columns[:total_index]
    
    # Créer un DataFrame pour chaque intervalle
    df_interval = df[columns].copy()
    
    # Récupérer le nom de la colonne de date
    date_S1 = df_interval.columns.to_list()[0]
    
    # Ajouter la colonne 'Date' au DataFrame
    df_interval['Date'] = date_S1
    
    # Renommer les colonnes avec la première ligne
    df_interval.columns = df_interval.iloc[0]
    
    # Supprimer les deux premières lignes et réinitialiser l'index
    df_interval = df_interval[2:].reset_index(drop=True)
    
    # Renommer la colonne 'Semaine XXXX XX' en 'Date'
    df_interval.rename(columns={date_S1: 'Date'}, inplace=True)
    
    # Ajouter les colonnes communes uniquement si elles existent dans df1
    if common_columns:
        df_interval = df_interval.join(df[common_columns])

    # Sélectionner uniquement les colonnes à conserver, y compris 'Date'
    if set(columns_to_keep).issubset(df_interval.columns):
        df_filtered = df_interval[columns_to_keep]
        filtered_dfs.append(df_filtered)

# Concaténer tous les DataFrames filtrés en un seul DataFrame
final_df = pd.concat(filtered_dfs, ignore_index=True)

# Afficher le DataFrame final
print("DataFrame unique après filtrage et concaténation :")
display(final_df)

DataFrame unique après filtrage et concaténation :

0   Tx conformite Tx SI avance Tx SI retard     Tx SI             Date
0        0.926288     0.015576     0.002528  0.018104  Semaine 2024 35
1             NaN          NaN          NaN       NaN  Semaine 2024 35
2        0.947664     0.015888            0  0.015888  Semaine 2024 35
3        0.980887     0.009939     0.000765  0.010703  Semaine 2024 35
4        0.952328     0.008869      0.00388  0.012749  Semaine 2024 35
..            ...          ...          ...       ...              ...
163      0.897561     0.004878     0.009756  0.014634  Semaine 2024 38
164         0.875     0.029412            0  0.029412  Semaine 2024 38
165      0.981818     0.018182            0  0.018182  Semaine 2024 38
166      0.884149     0.020359     0.004363  0.024721  Semaine 2024 38
167      0.930056     0.016524      0.00765  0.024174  Semaine 2024 38

[168 rows x 5 columns]

In [74]:
final_df.head(50)

0  Tx conformite Tx SI avance Tx SI retard     Tx SI             Date
0       0.926288     0.015576     0.002528  0.018104  Semaine 2024 35
1            NaN          NaN          NaN       NaN  Semaine 2024 35
2       0.947664     0.015888            0  0.015888  Semaine 2024 35
3       0.980887     0.009939     0.000765  0.010703  Semaine 2024 35
4       0.952328     0.008869      0.00388  0.012749  Semaine 2024 35
5            NaN          NaN          NaN       NaN  Semaine 2024 35
6       0.959989     0.008165     0.001633  0.009799  Semaine 2024 35
7       0.966903     0.013855     0.004002  0.017857  Semaine 2024 35
8       0.979186     0.008326     0.000308  0.008634  Semaine 2024 35
9       0.925339     0.011312     0.004309  0.015622  Semaine 2024 35
10      0.912613     0.009079     0.012322  0.021401  Semaine 2024 35
11      0.898671     0.036545     0.016196  0.052741  Semaine 2024 35
12        0.9416     0.007964     0.003792  0.011756  Semaine 2024 35
13      0.923048     0.008299     0.026405  0.034704  Semaine 2024 35
14      0.936541     0.026499     0.006974  0.033473  Semaine 2024 35
15      0.958333     0.014583     0.010417     0.025  Semaine 2024 35
16      0.954018     0.004537     0.001769  0.006305  Semaine 2024 35
17      0.965986     0.008098     0.000648  0.008746  Semaine 2024 35
18      0.943556     0.007526     0.002822  0.010348  Semaine 2024 35
19      0.977907     0.008337            0  0.008337  Semaine 2024 35
20      0.967647     0.017647     0.005882  0.023529  Semaine 2024 35
21      0.952116     0.021521     0.007174  0.028694  Semaine 2024 35
22      0.971079     0.014461     0.001112  0.015573  Semaine 2024 35
23      0.978846     0.015385     0.000962  0.016346  Semaine 2024 35
24      0.953435     0.022392     0.003053  0.025445  Semaine 2024 35
25      0.966056     0.014866     0.000496  0.015362  Semaine 2024 35
26      0.838578     0.031886     0.005664   0.03755  Semaine 2024 35
27      0.923581     0.011421     0.008062  0.019483  Semaine 2024 35
28           NaN          NaN          NaN       NaN  Semaine 2024 35
29      0.919954     0.005568     0.016241   0.02181  Semaine 2024 35
30      0.697183     0.274648     0.003521  0.278169  Semaine 2024 35
31      0.731602     0.047619     0.073593  0.121212  Semaine 2024 35
32           NaN          NaN          NaN       NaN  Semaine 2024 35
33           NaN          NaN          NaN       NaN  Semaine 2024 35
34           NaN          NaN          NaN       NaN  Semaine 2024 35
35           NaN          NaN          NaN       NaN  Semaine 2024 35
36           NaN          NaN          NaN       NaN  Semaine 2024 35
37           NaN          NaN          NaN       NaN  Semaine 2024 35
38           NaN          NaN          NaN       NaN  Semaine 2024 35
39      0.930016     0.032659     0.012442  0.045101  Semaine 2024 35
40      0.845931     0.010103     0.022451  0.032554  Semaine 2024 35
41      0.931777     0.013608       0.0058  0.019408  Semaine 2024 35
42      0.920407     0.017316     0.005316  0.022632  Semaine 2024 36
43      0.766323     0.041237     0.013746  0.054983  Semaine 2024 36
44      0.947853     0.011247            0  0.011247  Semaine 2024 36
45      0.958935     0.013538     0.002708  0.016245  Semaine 2024 36
46      0.966596     0.005626     0.006329  0.011955  Semaine 2024 36
47      0.864706     0.035294     0.011765  0.047059  Semaine 2024 36
48       0.92909     0.006189     0.001076  0.007266  Semaine 2024 36
49       0.94683     0.007402     0.002961  0.010363  Semaine 2024 36

In [80]:
# Dictionnaire pour stocker les DataFrames par intervalle
dataframes_by_interval = {}

# Liste des colonnes à conserver
columns_to_keep = ['Tx conformite', 'Tx SI avance', 'Tx SI retard', 'Tx SI', 'Date']

# Vérifier si toutes les colonnes nécessaires sont dans df1
common_columns = [col for col in columns_to_keep[:-1] if col in df.columns]

# Liste pour stocker les DataFrames filtrés
filtered_dfs = []

# Boucle sur chaque intervalle dans columns_by_interval
for idx, (interval, columns) in enumerate(columns_by_interval.items()):
    # Si c'est le dernier intervalle, exclure les colonnes à partir de 'Totaux'
    if idx == len(columns_by_interval) - 1:
        if 'Totaux' in columns:
            total_index = columns.index('Totaux')
            columns = columns[:total_index]
    
    # Créer un DataFrame pour chaque intervalle
    df_interval = df[columns].copy()
    
    # Récupérer le nom de la colonne de date
    date_S1 = df_interval.columns.to_list()[0]
    
    # Ajouter la colonne 'Date' au DataFrame
    df_interval['Date'] = date_S1
    
    # Renommer les colonnes avec la première ligne
    df_interval.columns = df_interval.iloc[0]
    
    # Supprimer les deux premières lignes et réinitialiser l'index
    df_interval = df_interval[2:].reset_index(drop=True)
    
    # Renommer la colonne 'Semaine XXXX XX' en 'Date'
    df_interval.rename(columns={date_S1: 'Date'}, inplace=True)
    
    # Ajouter les colonnes communes uniquement si elles existent dans df1
    if common_columns:
        df_interval = df_interval.join(df[common_columns])
    
    # Supprimer la dernière ligne avant le filtrage
    df_interval = df_interval[:-1]
    
    # Sélectionner uniquement les colonnes à conserver, y compris 'Date'
    if set(columns_to_keep).issubset(df_interval.columns):
        df_filtered = df_interval[columns_to_keep]
        filtered_dfs.append(df_filtered)

# Concaténer tous les DataFrames filtrés en un seul DataFrame
final_df = pd.concat(filtered_dfs, ignore_index=True)

# Afficher le DataFrame final
print("DataFrame unique après filtrage et concaténation :")
display(final_df)

DataFrame unique après filtrage et concaténation :

0   Tx conformite Tx SI avance Tx SI retard     Tx SI             Date
0        0.926288     0.015576     0.002528  0.018104  Semaine 2024 35
1             NaN          NaN          NaN       NaN  Semaine 2024 35
2        0.947664     0.015888            0  0.015888  Semaine 2024 35
3        0.980887     0.009939     0.000765  0.010703  Semaine 2024 35
4        0.952328     0.008869      0.00388  0.012749  Semaine 2024 35
..            ...          ...          ...       ...              ...
159      0.947059            0            0         0  Semaine 2024 38
160      0.897561     0.004878     0.009756  0.014634  Semaine 2024 38
161         0.875     0.029412            0  0.029412  Semaine 2024 38
162      0.981818     0.018182            0  0.018182  Semaine 2024 38
163      0.884149     0.020359     0.004363  0.024721  Semaine 2024 38

[164 rows x 5 columns]

In [81]:
final_df.head(50)

0  Tx conformite Tx SI avance Tx SI retard     Tx SI             Date
0       0.926288     0.015576     0.002528  0.018104  Semaine 2024 35
1            NaN          NaN          NaN       NaN  Semaine 2024 35
2       0.947664     0.015888            0  0.015888  Semaine 2024 35
3       0.980887     0.009939     0.000765  0.010703  Semaine 2024 35
4       0.952328     0.008869      0.00388  0.012749  Semaine 2024 35
5            NaN          NaN          NaN       NaN  Semaine 2024 35
6       0.959989     0.008165     0.001633  0.009799  Semaine 2024 35
7       0.966903     0.013855     0.004002  0.017857  Semaine 2024 35
8       0.979186     0.008326     0.000308  0.008634  Semaine 2024 35
9       0.925339     0.011312     0.004309  0.015622  Semaine 2024 35
10      0.912613     0.009079     0.012322  0.021401  Semaine 2024 35
11      0.898671     0.036545     0.016196  0.052741  Semaine 2024 35
12        0.9416     0.007964     0.003792  0.011756  Semaine 2024 35
13      0.923048     0.008299     0.026405  0.034704  Semaine 2024 35
14      0.936541     0.026499     0.006974  0.033473  Semaine 2024 35
15      0.958333     0.014583     0.010417     0.025  Semaine 2024 35
16      0.954018     0.004537     0.001769  0.006305  Semaine 2024 35
17      0.965986     0.008098     0.000648  0.008746  Semaine 2024 35
18      0.943556     0.007526     0.002822  0.010348  Semaine 2024 35
19      0.977907     0.008337            0  0.008337  Semaine 2024 35
20      0.967647     0.017647     0.005882  0.023529  Semaine 2024 35
21      0.952116     0.021521     0.007174  0.028694  Semaine 2024 35
22      0.971079     0.014461     0.001112  0.015573  Semaine 2024 35
23      0.978846     0.015385     0.000962  0.016346  Semaine 2024 35
24      0.953435     0.022392     0.003053  0.025445  Semaine 2024 35
25      0.966056     0.014866     0.000496  0.015362  Semaine 2024 35
26      0.838578     0.031886     0.005664   0.03755  Semaine 2024 35
27      0.923581     0.011421     0.008062  0.019483  Semaine 2024 35
28           NaN          NaN          NaN       NaN  Semaine 2024 35
29      0.919954     0.005568     0.016241   0.02181  Semaine 2024 35
30      0.697183     0.274648     0.003521  0.278169  Semaine 2024 35
31      0.731602     0.047619     0.073593  0.121212  Semaine 2024 35
32           NaN          NaN          NaN       NaN  Semaine 2024 35
33           NaN          NaN          NaN       NaN  Semaine 2024 35
34           NaN          NaN          NaN       NaN  Semaine 2024 35
35           NaN          NaN          NaN       NaN  Semaine 2024 35
36           NaN          NaN          NaN       NaN  Semaine 2024 35
37           NaN          NaN          NaN       NaN  Semaine 2024 35
38           NaN          NaN          NaN       NaN  Semaine 2024 35
39      0.930016     0.032659     0.012442  0.045101  Semaine 2024 35
40      0.845931     0.010103     0.022451  0.032554  Semaine 2024 35
41      0.920407     0.017316     0.005316  0.022632  Semaine 2024 36
42      0.766323     0.041237     0.013746  0.054983  Semaine 2024 36
43      0.947853     0.011247            0  0.011247  Semaine 2024 36
44      0.958935     0.013538     0.002708  0.016245  Semaine 2024 36
45      0.966596     0.005626     0.006329  0.011955  Semaine 2024 36
46      0.864706     0.035294     0.011765  0.047059  Semaine 2024 36
47       0.92909     0.006189     0.001076  0.007266  Semaine 2024 36
48       0.94683     0.007402     0.002961  0.010363  Semaine 2024 36
49      0.957199     0.006283     0.002618  0.008901  Semaine 2024 36

In [84]:
# Ajouter la colonne 'Ligne' à chaque intervalle dans columns_by_interval
for interval in columns_by_interval:
    columns_by_interval[interval] = ['Ligne'] + columns_by_interval[interval]

# Dictionnaire pour stocker les DataFrames par intervalle
dataframes_by_interval = {}

# Liste des colonnes à conserver
columns_to_keep = ['Ligne','Tx conformite', 'Tx SI avance', 'Tx SI retard', 'Tx SI', 'Date']

# Vérifier si toutes les colonnes nécessaires sont dans df1
common_columns = [col for col in columns_to_keep[:-1] if col in df.columns]

# Liste pour stocker les DataFrames filtrés
filtered_dfs = []

# Boucle sur chaque intervalle dans columns_by_interval
for idx, (interval, columns) in enumerate(columns_by_interval.items()):
    # Si c'est le dernier intervalle, exclure les colonnes à partir de 'Totaux'
    if idx == len(columns_by_interval) - 1:
        if 'Totaux' in columns:
            total_index = columns.index('Totaux')
            columns = columns[:total_index]
    
    # Créer un DataFrame pour chaque intervalle
    df_interval = df[columns].copy()
    
    # Récupérer le nom de la colonne de date
    date_S1 = df_interval.columns.to_list()[1]  # Prendre le nom de la deuxième colonne (car la première est 'Ligne')
    
    # Ajouter la colonne 'Date' au DataFrame
    df_interval['Date'] = date_S1
    
    # Renommer les colonnes avec la première ligne
    df_interval.columns = df_interval.iloc[0]
    
    # Supprimer les deux premières lignes et réinitialiser l'index
    df_interval = df_interval[2:].reset_index(drop=True)
    
    # Renommer la colonne 'Semaine XXXX XX' en 'Date'
    df_interval.rename(columns={date_S1: 'Date'}, inplace=True)
    
    # Ajouter les colonnes communes uniquement si elles existent dans df1
    if common_columns:
        df_interval = df_interval.join(df[common_columns])
    
    # Supprimer la dernière ligne avant le filtrage
    df_interval = df_interval[:-1]
    
    # Sélectionner uniquement les colonnes à conserver, y compris 'Date'
    if set(columns_to_keep).issubset(df_interval.columns):
        df_filtered = df_interval[columns_to_keep]
        filtered_dfs.append(df_filtered)

# Concaténer tous les DataFrames filtrés en un seul DataFrame
final_df = pd.concat(filtered_dfs, ignore_index=True)

# Afficher le DataFrame final
print("DataFrame unique après filtrage et concaténation :")
display(final_df)

KeyError: "['Ligne'] not in index"

In [90]:
filename = 'C:/Users/albert-marc.talla/Desktop/test/Taux de régularité DSP - 18092024131617.xlsx'

df = pd.read_excel(filename, header=11)

In [95]:
print(df.head(2))

     Transporteur Semaine 2024 35    Unnamed: 2    Unnamed: 3 Unnamed: 4  \
0           Ligne   Tx conformite  Tx SI avance  Tx SI retard      Tx SI
1  DSP19 - SENART        0.931777      0.013608        0.0058   0.019408

  Semaine 2024 36    Unnamed: 6    Unnamed: 7 Unnamed: 8 Semaine 2024 37  ...  \
0   Tx conformite  Tx SI avance  Tx SI retard      Tx SI   Tx conformite  ...
1        0.921553      0.013807      0.008999   0.022806        0.920352  ...

    Unnamed: 11 Unnamed: 12 Semaine 2024 38   Unnamed: 14   Unnamed: 15  \
0  Tx SI retard       Tx SI   Tx conformite  Tx SI avance  Tx SI retard
1      0.007891    0.025049        0.930056      0.016524       0.00765

  Unnamed: 16         Totaux   Unnamed: 18   Unnamed: 19 Unnamed: 20
0       Tx SI  Tx conformite  Tx SI avance  Tx SI retard       Tx SI
1    0.024174       0.924892      0.015167      0.007641    0.022808

[2 rows x 21 columns]

In [91]:
# Fonction pour récupérer les paires start_week et end_week, incluant la dernière semaine si non suivie
def get_week_intervals(df):
    week_columns = [col for col in df.columns if 'Semaine' in col]
    intervals = []
    for i in range(len(week_columns) - 1):
        start_week = week_columns[i]
        end_week = week_columns[i + 1]
        intervals.append((start_week, end_week))
    # Ajouter la dernière semaine seule si elle n'a pas d'intervalle suivant
    if len(week_columns) > 0:
        intervals.append((week_columns[-1], None))
    return intervals

# Fonction pour récupérer les colonnes entre deux semaines, incluant le cas où end_week est None
def get_columns_between_weeks_exclusive(df, start_week, end_week):
    selected_columns = []
    include = False
    for col in df.columns:
        if start_week in col:
            include = True
        if include:
            # Si end_week est None, inclure toutes les colonnes restantes
            if end_week is None:
                selected_columns.append(col)
            # Sinon, arrêter l'inclusion avant d'atteindre end_week
            elif end_week in col:
                break
            else:
                selected_columns.append(col)
    return selected_columns

# Récupérer les paires de semaines
week_intervals = get_week_intervals(df)

# Initialiser un dictionnaire pour stocker les colonnes par intervalle
columns_by_interval = {}

# Boucle sur chaque intervalle (start_week, end_week) pour récupérer les colonnes
for start_week, end_week in week_intervals:
    # Récupérer les colonnes pour cet intervalle spécifique
    interval_columns = get_columns_between_weeks_exclusive(df, start_week, end_week)
    # Stocker le résultat dans le dictionnaire avec l'intervalle comme clé
    columns_by_interval[(start_week, end_week)] = interval_columns

# Afficher les colonnes pour chaque intervalle
for interval, columns in columns_by_interval.items():
    print(f"Intervalle {interval}: {columns}")

Intervalle ('Semaine 2024 35', 'Semaine 2024 36'): ['Semaine 2024 35', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4']
Intervalle ('Semaine 2024 36', 'Semaine 2024 37'): ['Semaine 2024 36', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8']
Intervalle ('Semaine 2024 37', 'Semaine 2024 38'): ['Semaine 2024 37', 'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12']
Intervalle ('Semaine 2024 38', None): ['Semaine 2024 38', 'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Totaux', 'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20']

In [92]:
 df['Ligne']

KeyError: 'Ligne'

In [87]:
# Vérifiez si 'Ligne' est dans les colonnes, sinon ajoutez-la
if 'Ligne' not in df.columns:
    df['Ligne'] = range(1, len(df) + 1)  # Ajoute une colonne 'Ligne' avec des valeurs numériques
    

# Ajouter la colonne 'Ligne' à chaque intervalle dans columns_by_interval
for interval in columns_by_interval:
    columns_by_interval[interval] = ['Ligne'] + columns_by_interval[interval]

# Dictionnaire pour stocker les DataFrames par intervalle
dataframes_by_interval = {}

# Liste des colonnes à conserver
columns_to_keep = ['Ligne', 'Tx conformite', 'Tx SI avance', 'Tx SI retard', 'Tx SI', 'Date']

# Vérifier si toutes les colonnes nécessaires sont dans df
common_columns = [col for col in columns_to_keep[:-1] if col in df.columns]

# Liste pour stocker les DataFrames filtrés
filtered_dfs = []

# Boucle sur chaque intervalle dans columns_by_interval
for idx, (interval, columns) in enumerate(columns_by_interval.items()):
    # Si c'est le dernier intervalle, exclure les colonnes à partir de 'Totaux'
    if idx == len(columns_by_interval) - 1:
        if 'Totaux' in columns:
            total_index = columns.index('Totaux')
            columns = columns[:total_index]
    
    # Créer un DataFrame pour chaque intervalle
    df_interval = df[columns].copy()
    
    # Récupérer le nom de la colonne de date
    date_S1 = df_interval.columns.to_list()[1]  # Prendre le nom de la deuxième colonne (car la première est 'Ligne')
    
    # Ajouter la colonne 'Date' au DataFrame
    df_interval['Date'] = date_S1
    
    # Renommer les colonnes avec la première ligne
    df_interval.columns = df_interval.iloc[0]
    
    # Supprimer les deux premières lignes et réinitialiser l'index
    df_interval = df_interval[2:].reset_index(drop=True)
    
    # Renommer la colonne 'Semaine XXXX XX' en 'Date'
    df_interval.rename(columns={date_S1: 'Date'}, inplace=True)
    
    # Ajouter les colonnes communes uniquement si elles existent dans df
    if common_columns:
        df_interval = df_interval.join(df[common_columns])
    
    # Supprimer la dernière ligne avant le filtrage
    df_interval = df_interval[:-1]
    
    # Sélectionner uniquement les colonnes à conserver, y compris 'Date'
    if set(columns_to_keep).issubset(df_interval.columns):
        df_filtered = df_interval[columns_to_keep]
        filtered_dfs.append(df_filtered)

# Concaténer tous les DataFrames filtrés en un seul DataFrame
final_df = pd.concat(filtered_dfs, ignore_index=True)

# Afficher le DataFrame final
print("DataFrame unique après filtrage et concaténation :")
display(final_df)

DataFrame unique après filtrage et concaténation :

     Ligne Tx conformite Tx SI avance Tx SI retard     Tx SI             Date
0        1      0.926288     0.015576     0.002528  0.018104  Semaine 2024 35
1        2           NaN          NaN          NaN       NaN  Semaine 2024 35
2        3      0.947664     0.015888            0  0.015888  Semaine 2024 35
3        4      0.980887     0.009939     0.000765  0.010703  Semaine 2024 35
4        5      0.952328     0.008869      0.00388  0.012749  Semaine 2024 35
..     ...           ...          ...          ...       ...              ...
159     37      0.947059            0            0         0  Semaine 2024 38
160     38      0.897561     0.004878     0.009756  0.014634  Semaine 2024 38
161     39         0.875     0.029412            0  0.029412  Semaine 2024 38
162     40      0.981818     0.018182            0  0.018182  Semaine 2024 38
163     41      0.884149     0.020359     0.004363  0.024721  Semaine 2024 38

[164 rows x 6 columns]

In [96]:
# Ajouter la colonne 'Ligne' à chaque intervalle dans columns_by_interval
for interval in columns_by_interval:
    columns_by_interval[interval] = ['Ligne'] + columns_by_interval[interval]

# Dictionnaire pour stocker les DataFrames par intervalle
dataframes_by_interval = {}

# Liste des colonnes à conserver
columns_to_keep = ['Ligne', 'Tx conformite', 'Tx SI avance', 'Tx SI retard', 'Tx SI', 'Date']

# Vérifier si toutes les colonnes nécessaires sont dans df
common_columns = [col for col in columns_to_keep[:-1] if col in df.columns]

# Liste pour stocker les DataFrames filtrés
filtered_dfs = []

# Boucle sur chaque intervalle dans columns_by_interval
for idx, (interval, columns) in enumerate(columns_by_interval.items()):
    # Si c'est le dernier intervalle, exclure les colonnes à partir de 'Totaux'
    if idx == len(columns_by_interval) - 1:
        if 'Totaux' in columns:
            total_index = columns.index('Totaux')
            columns = columns[:total_index]
    
    # Créer un DataFrame pour chaque intervalle
    df_interval = df[columns].copy()
    
    # Récupérer le nom de la colonne de date
    date_S1 = df_interval.columns.to_list()[1]  # Prendre le nom de la deuxième colonne (car la première est 'Ligne')
    
    # Ajouter la colonne 'Date' au DataFrame
    df_interval['Date'] = date_S1
    
    # Renommer les colonnes avec la première ligne
    df_interval.columns = df_interval.iloc[0]
    
    # Supprimer les deux premières lignes et réinitialiser l'index
    df_interval = df_interval[2:].reset_index(drop=True)
    
    # Renommer la colonne 'Semaine XXXX XX' en 'Date'
    df_interval.rename(columns={date_S1: 'Date'}, inplace=True)
    
    # Ajouter les colonnes communes uniquement si elles existent dans df
    if common_columns:
        df_interval = df_interval.join(df[common_columns])
    
    # Supprimer la dernière ligne avant le filtrage
    df_interval = df_interval[:-1]
    
    # Sélectionner uniquement les colonnes à conserver, y compris 'Date'
    if set(columns_to_keep).issubset(df_interval.columns):
        df_filtered = df_interval[columns_to_keep]
        filtered_dfs.append(df_filtered)

# Concaténer tous les DataFrames filtrés en un seul DataFrame
final_df = pd.concat(filtered_dfs, ignore_index=True)

# Afficher le DataFrame final
print("DataFrame unique après filtrage et concaténation :")
display(final_df)

KeyError: "['Ligne'] not in index"

In [97]:
# Dictionnaire pour stocker les DataFrames par intervalle
dataframes_by_interval = {}

# Liste des colonnes à conserver
columns_to_keep = ['Ligne', 'Tx conformite', 'Tx SI avance', 'Tx SI retard', 'Tx SI', 'Date']

# Vérifier si toutes les colonnes nécessaires sont dans df
common_columns = [col for col in columns_to_keep[:-1] if col in df.columns]

# Liste pour stocker les DataFrames filtrés
filtered_dfs = []

# Boucle sur chaque intervalle dans columns_by_interval
for idx, (interval, columns) in enumerate(columns_by_interval.items()):
    # Si c'est le dernier intervalle, exclure les colonnes à partir de 'Totaux'
    if idx == len(columns_by_interval) - 1:
        if 'Totaux' in columns:
            total_index = columns.index('Totaux')
            columns = columns[:total_index]
    
    # Créer un DataFrame pour chaque intervalle
    df_interval = df[columns].copy()
    
    # Récupérer le nom de la colonne de date
    date_S1 = df_interval.columns.to_list()[1]  # Prendre le nom de la deuxième colonne (car la première est 'Ligne')
    
    # Utiliser la première ligne comme en-tête des colonnes
    df_interval.columns = df_interval.iloc[0]
    
    # Supprimer les deux premières lignes et réinitialiser l'index
    df_interval = df_interval[2:].reset_index(drop=True)
    
    # Ajouter la colonne 'Date' au DataFrame avec la valeur de la date récupérée
    df_interval['Date'] = date_S1
    
    # Ajouter les colonnes communes uniquement si elles existent dans df
    if common_columns:
        df_interval = df_interval.join(df[common_columns])
    
    # Supprimer la dernière ligne avant le filtrage
    df_interval = df_interval[:-1]
    
    # Sélectionner uniquement les colonnes à conserver, y compris 'Date'
    if set(columns_to_keep).issubset(df_interval.columns):
        df_filtered = df_interval[columns_to_keep]
        filtered_dfs.append(df_filtered)

# Concaténer tous les DataFrames filtrés en un seul DataFrame
final_df = pd.concat(filtered_dfs, ignore_index=True)

# Afficher le DataFrame final
print("DataFrame unique après filtrage et concaténation :")
display(final_df)

KeyError: "['Ligne'] not in index"

In [106]:
# Supposons que columns_by_interval ait été créé comme dans l'exemple précédent
columns_by_interval = {
    ('Semaine 2024 35', 'Semaine 2024 36'): ['Ligne', 'Semaine 2024 35', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4'],
    ('Semaine 2024 36', 'Semaine 2024 37'): ['Ligne', 'Semaine 2024 36', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8'],
    ('Semaine 2024 37', 'Semaine 2024 38'): ['Ligne', 'Semaine 2024 37', 'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12'],
    ('Semaine 2024 38', None): ['Ligne', 'Semaine 2024 38', 'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Totaux', 'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20']
}

# Dictionnaire pour stocker les DataFrames par intervalle
dataframes_by_interval = {}

# Liste des colonnes à conserver
columns_to_keep = ['Ligne', 'Tx conformite', 'Tx SI avance', 'Tx SI retard', 'Tx SI', 'Date']

# Vérifier si toutes les colonnes nécessaires sont dans df
common_columns = [col for col in columns_to_keep[:-1] if col in df.columns]

# Liste pour stocker les DataFrames filtrés
filtered_dfs = []

# Boucle sur chaque intervalle dans columns_by_interval
for idx, (interval, columns) in enumerate(columns_by_interval.items()):
    # Si c'est le dernier intervalle, exclure les colonnes à partir de 'Totaux'
    if idx == len(columns_by_interval) - 1:
        if 'Totaux' in columns:
            total_index = columns.index('Totaux')
            columns = columns[:total_index]
    
    # Créer un DataFrame pour chaque intervalle
    df_interval = df[columns].copy()
    
    # Récupérer le nom de la colonne de date
    date_S1 = df_interval.columns.to_list()[1]  # Prendre le nom de la deuxième colonne (car la première est 'Ligne')
    
    # Ajouter la colonne 'Date' au DataFrame
    df_interval['Date'] = date_S1
    
    # Renommer les colonnes avec la première ligne
    df_interval.columns = df_interval.iloc[0]
    
    # Supprimer les deux premières lignes et réinitialiser l'index
    df_interval = df_interval[2:].reset_index(drop=True)
    
    # Renommer la colonne 'Semaine XXXX XX' en 'Date'
    df_interval.rename(columns={date_S1: 'Date'}, inplace=True)
    
    # Sélectionner uniquement les colonnes à conserver, y compris 'Date'
    if set(columns_to_keep).issubset(df_interval.columns):
        df_filtered = df_interval[columns_to_keep]
        filtered_dfs.append(df_filtered)

# Concaténer tous les DataFrames filtrés en un seul DataFrame
final_df = pd.concat(filtered_dfs, ignore_index=True)

# Afficher le DataFrame final
print("DataFrame unique après filtrage et concaténation :")
display(final_df)

KeyError: "['Ligne'] not in index"